server:
  port: 9090
spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/SpringBD
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
